services:
  # ml-service:
  #   build: ./backend/ml-service
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend/ml-service:/app
  #   networks:
  #     - backend

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./frontend:/app

  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - backend

  # mongodb-service:
  #   build: ./backend/mongodb-service
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./backend/mongodb-service:/app
  #   networks:
  #     - backend

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  redis-service:
    build: ./backend/redis-service
    ports:
      - "8002:8002"
    depends_on:
      - redis
    volumes:
      - ./backend/redis-service:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data: