version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongodb-service:
    build:
      context: ./backend/mongodb-service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    volumes:
      - ./backend/mongodb-service:/app

volumes:
  mongodb_data: