import os

MONGODB_SERVICE_HOST = os.getenv("MONGODB_SERVICE_HOST", "mongodb-service")
MONGODB_SERVICE_PORT = int(os.getenv("MONGODB_SERVICE_PORT", 8001))
MONGODB_SERVICE_ENDPOINTS = {
    "POINTS": f"http://{MONGODB_SERVICE_HOST}:{MONGODB_SERVICE_PORT}/points",
    "USERS": f"http://{MONGODB_SERVICE_HOST}:{MONGODB_SERVICE_PORT}/users",
    "CLUSTERS": f"http://{MONGODB_SERVICE_HOST}:{MONGODB_SERVICE_PORT}/clusters",
    "EMOTIONS": f"http://{MONGODB_SERVICE_HOST}:{MONGODB_SERVICE_PORT}/emotions",
}

REDIS_SERVICE_HOST = os.getenv("REDIS_SERVICE_HOST", "redis-service")
REDIS_SERVICE_PORT = int(os.getenv("REDIS_SERVICE_PORT", 8002))
REDIS_SERVICE_ENDPOINTS = {
    "VALUES": f"http://{REDIS_SERVICE_HOST}:{REDIS_SERVICE_PORT}/values"
}

INCREMENT_NUMBER = 1

NB_WC_PREFIX = "nb:wc"
